# -*- coding: utf-8 -*-
"""FSW_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4EXLydl1svfpwUwRg-aiv8j3VUccNyI
"""

import streamlit as st

# Define the equations for each series
def calculate_dimensions(series, thickness):
    if series == "2XXX":
        shoulder_diameter = 1.0449 * thickness + 13.156
        pin_diameter = 0.3945 * thickness + 6.1592
        pin_length = 0.9663 * thickness + 0.0602
    elif series == "5XXX":
        shoulder_diameter = 1.9129 * thickness + 7.5079
        pin_diameter = 0.1811 * thickness + 5.5237
        pin_length = 0.9894 * thickness - 0.1755
    elif series == "6XXX":
        shoulder_diameter = 1.3412 * thickness + 10.726
        pin_diameter = 0.6837 * thickness + 2.5443
        pin_length = 0.9732 * thickness - 0.2093
    elif series == "7XXX":
        shoulder_diameter = 1.1311 * thickness + 11.291
        pin_diameter = 0.6231 * thickness + 2.1772
        pin_length = 0.9464 * thickness - 0.0566
    else:
        raise ValueError("Invalid series")

    return shoulder_diameter, pin_diameter, pin_length

# Streamlit app
st.title("AlloyTool Designer")
st.image("tool.png")
st.write("Enter the aluminum alloy series and thickness to calculate tool dimensions.")

# User input
series = st.selectbox("Select Aluminum Alloy Series", ["2XXX", "5XXX", "6XXX", "7XXX"])
thickness = st.number_input("Enter the Thickness (mm)", min_value=0.0, step=0.1)

# Calculate and display results
if st.button("Calculate"):
    shoulder_diameter, pin_diameter, pin_length = calculate_dimensions(series, thickness)
    st.write(f"### Results for {series} Series")
    st.write(f"**Shoulder Diameter:** {shoulder_diameter:.2f} mm")
    st.write(f"**Pin Diameter:** {pin_diameter:.2f} mm")
    st.write(f"**Pin Length:** {pin_length:.2f} mm")

if __name__ == "__main__":
    main()
